server:
  port: 8088
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    message: Thank you for registering. Please click on the below link activate your account.
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    protocol: smtp
    test-connection: false
  profiles:
    active: local
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    show-sql: false
    database: postgresql
    generate-ddl: true
    open-in-view: true
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
          time_zone: UTC
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
logging:
  level:
    org.springframework: warn
    com.zaxxer.hikari: warn
    org.hibernate: warn
    org.apache: warn
aws:
  login: ${AWS_ACCESS_KEY}
  password: ${AWS_SECRET_ACCESS_KEY}
amazon-client:
  s3:
    bucket-name: friendsapp-avatar-bucket
